name: Check Firefox Packages

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gzip

      - name: Run Firefox checker
        id: check # add step id so we can read outputs
        run: |
          mkdir -p firefox/latest

          ARCHS=("aarch64" "arm" "x86_64" "i686")
          REPO_URL="https://packages-cf.termux.dev/apt/termux-x11/dists/x11/main"

          updated=0

          for arch in "${ARCHS[@]}"; do
            echo "Checking for $arch..."

            wget -qO - "$REPO_URL/binary-$arch/Packages.gz" | zgrep -A 10 '^Package: firefox$' > tmp.txt

            version=$(grep '^Version:' tmp.txt | head -n1 | sed 's/Version: //')
            filename=$(grep '^Filename:' tmp.txt | head -n1 | sed 's/Filename: //')

            echo "Found version: $version"
            echo "Filename: $filename"

            verfile="firefox/latest/firefox_version_${arch}.txt"
            debfile="firefox/latest/firefox_latest_${arch}.deb"

            oldver=$(cat "$verfile" 2>/dev/null || echo "none")

            if [ "$version" != "$oldver" ] || [ ! -f "$debfile" ]; then
              echo "Updating $arch..."
              wget -O "$debfile" "https://packages-cf.termux.dev/apt/termux-x11/$filename"
              echo "$version" > "$verfile"
              updated=1
            else
              echo "$arch is already up to date."
            fi

            rm -f tmp.txt
          done

          echo "updated=$updated" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.check.outputs.updated == '1'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add firefox/latest/*
          version=$(cat firefox/latest/firefox_version_aarch64.txt)
          git commit -m "Update Firefox to version $version"

          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
