name: Check Firefox Packages

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, arm, x86_64, i686]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gzip xz-utils zstd tar tree

      - name: Run Firefox checker for ${{ matrix.arch }}
        id: check
        run: |
          ARCH="${{ matrix.arch }}"
          mkdir -p firefox/latest
          REPO_URL="https://packages-cf.termux.dev/apt/termux-x11/dists/x11/main"
          updated=0

          echo "Checking for $ARCH..."

          wget -qO - "$REPO_URL/binary-$ARCH/Packages.gz" | zgrep -A 10 '^Package: firefox$' > tmp.txt

          version=$(grep '^Version:' tmp.txt | head -n1 | sed 's/Version: //')
          filename=$(grep '^Filename:' tmp.txt | head -n1 | sed 's/Filename: //')

          echo "Found version: $version"
          echo "Filename: $filename"

          verfile="firefox/latest/firefox_version_${ARCH}.txt"
          archivefile="firefox_latest_${ARCH}.tar.xz"

          oldver=$(cat "$verfile" 2>/dev/null || echo "none")

          if [ "$version" != "$oldver" ]; then
            echo "Updating $ARCH..."

            debfile="firefox_${ARCH}.deb"
            wget -O "$debfile" "https://packages-cf.termux.dev/apt/termux-x11/$filename"

            workdir="$(pwd)/deb_extract_temp_$ARCH"
            rm -rf "$workdir"
            mkdir -p "$workdir"
            
            ar x "$debfile" --output="$workdir"

            if [ -f "$workdir/data.tar.xz" ]; then
              tar -xf "$workdir/data.tar.xz" -C "$workdir"
            elif [ -f "$workdir/data.tar.zst" ]; then
              tar --zstd -xf "$workdir/data.tar.zst" -C "$workdir"
            elif [ -f "$workdir/data.tar.gz" ]; then
              tar -xf "$workdir/data.tar.gz" -C "$workdir"
            else
              echo "Error: data.tar.* not found in the .deb"
              exit 1
            fi

            firefox_source="$workdir/data/data/com.termux/files/usr/lib/firefox"
            if [ -d "$firefox_source" ]; then
              cp -a "$firefox_source" "./firefox_temp_$ARCH"
            else
              echo "Error: Firefox folder not found at expected path"
              exit 1
            fi

            tar -cJf "$archivefile" "firefox_temp_$ARCH"

            echo "$version" > "$verfile"

            rm -rf "$workdir" "$debfile" "firefox_temp_$ARCH"
            updated=1
          else
            echo "$ARCH is already up to date."
          fi

          rm -f tmp.txt
          echo "updated=$updated" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Upload versioned Release
        if: steps.check.outputs.updated == '1'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: firefox-${{ matrix.arch }}-v${{ steps.check.outputs.version }}
          name: Firefox ${{ matrix.arch }} v${{ steps.check.outputs.version }}
          files: firefox_latest_${{ matrix.arch }}.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update latest tag (firefox-${{ matrix.arch }}-latest)
        if: steps.check.outputs.updated == '1'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          tag_name="firefox-${{ matrix.arch }}-latest"

          # Delete old latest tag if exists
          git push --delete origin $tag_name || true

          # Create lightweight latest tag and push
          git tag $tag_name
          git push origin $tag_name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
