name: Check Firefox Packages

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours starting from 00:00 UTC
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, arm, x86_64, i686]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gzip xz-utils zstd tar tree

      - name: Run Firefox checker for ${{ matrix.arch }}
        id: check
        run: |
          ARCH="${{ matrix.arch }}"
          mkdir -p firefox/latest
          REPO_URL="https://packages-cf.termux.dev/apt/termux-x11/dists/x11/main"
          updated=0

          echo "Checking for $ARCH..."

          wget -qO - "$REPO_URL/binary-$ARCH/Packages.gz" | zgrep -A 10 '^Package: firefox$' > tmp.txt

          version=$(grep '^Version:' tmp.txt | head -n1 | sed 's/Version: //')
          filename=$(grep '^Filename:' tmp.txt | head -n1 | sed 's/Filename: //')

          echo "Found version: $version"
          echo "Filename: $filename"

          verfile="firefox/latest/firefox_version_${ARCH}.txt"
          archivefile="firefox/latest/firefox_latest_${ARCH}.tar.xz"

          oldver=$(cat "$verfile" 2>/dev/null || echo "none")

          if [ "$version" != "$oldver" ] || [ ! -f "$archivefile" ]; then
            echo "Updating $ARCH..."

            debfile="firefox_${ARCH}.deb"
            wget -O "$debfile" "https://packages-cf.termux.dev/apt/termux-x11/$filename"

            workdir="$(pwd)/deb_extract_temp_$ARCH"
            rm -rf "$workdir" firefox
            mkdir -p "$workdir"
            
            ar x "$debfile" --output="$workdir"

            if [ -f "$workdir/data.tar.xz" ]; then
              tar -xvf "$workdir/data.tar.xz" -C "$workdir"
            elif [ -f "$workdir/data.tar.zst" ]; then
              tar --zstd -xf "$workdir/data.tar.zst" -C "$workdir"
            elif [ -f "$workdir/data.tar.gz" ]; then
              tar -xvf "$workdir/data.tar.gz" -C "$workdir"
            else
              echo "Error: data.tar.* not found in the .deb"
              exit 1
            fi

            firefox_source="$workdir/data/data/com.termux/files/usr/lib/firefox"
            if [ -d "$firefox_source" ]; then
              cp -a "$firefox_source" "firefox"
            else
              echo "Error: Firefox folder not found at expected path"
              exit 1
            fi

            tar -cJf "$archivefile" firefox

            rm -rf "$workdir" "$debfile" firefox

            echo "$version" > "$verfile"
            updated=1
          else
            echo "$ARCH is already up to date."
          fi

          rm -f tmp.txt
          echo "updated=$updated" >> $GITHUB_OUTPUT

      - name: Upload archive as artifact
        if: steps.check.outputs.updated == '1'
        uses: actions/upload-artifact@v4
        with:
          name: firefox_${{ matrix.arch }}
          path: |
            firefox/latest/firefox_latest_${{ matrix.arch }}.tar.xz
            firefox/latest/firefox_version_${{ matrix.arch }}.txt

  release:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Show downloaded files
        run: |
          tree artifacts

      - name: Delete existing latest release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          gh release delete latest -y || echo "No existing release to delete"
          git push --delete origin latest || echo "No existing tag to delete"

      - name: Create new latest release with all archives
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create latest \
            artifacts/firefox_aarch64/firefox_latest_aarch64.tar.xz \
            artifacts/firefox_arm/firefox_latest_arm.tar.xz \
            artifacts/firefox_x86_64/firefox_latest_x86_64.tar.xz \
            artifacts/firefox_i686/firefox_latest_i686.tar.xz \
            --title "Latest Firefox Archives" \
            --notes "This release contains the latest Firefox builds for all supported architectures."
